DROP TABLE venda_produtos;
DROP TABLE produto;
DROP TABLE venda;
DROP TABLE dependentes;
DROP TABLE cliente;
DROP TABLE telefones_transportadora;
DROP TABLE transportadora;
DROP TABLE telefones_empregado;
DROP TABLE atuacao_empregado;
DROP TABLE empregado;
DROP TABLE regiao;
DROP TABLE fornecedor;
DROP TABLE categoria;


CREATE TABLE cliente (
    idCliente INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    sobrenome VARCHAR(128) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    titulo_tratamento VARCHAR(20) NOT NULL,
    dt_nascimento DATE NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    rua VARCHAR(128) NOT NULL,
    num INT,
    bairro VARCHAR(128) NOT NULL,
    cidade VARCHAR(128) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    pais VARCHAR(20) NOT NULL,
    cep VARCHAR(9) NOT NULL
);

CREATE TABLE fornecedor (
    idFornecedor INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    telefone INT,
    homepage VARCHAR(128) NOT NULL
);

CREATE TABLE transportadora (
    idTransportadora INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL
);

CREATE TABLE empregado (
    matricula INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mat_supervisor INT NOT NULL,
    nome VARCHAR(128) NOT NULL,
    funcao VARCHAR(128) NOT NULL,
    dt_nascimento DATE NOT NULL,
    dt_contrato DATE NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    salario FLOAT(20),
    FOREIGN KEY (mat_supervisor) REFERENCES empregado(matricula)

);


CREATE TABLE venda (
    idVenda INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL REFERENCES cliente(idCliente),
    id_transportadora INT NOT NULL REFERENCES transportadora(idTransportadora),
    matricula INT NOT NULL REFERENCES empregado(matricula),
    frete VARCHAR(128) NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    dt_entrega VARCHAR(10) NOT NULL
);

CREATE TABLE categoria (
    idCategoria INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL
);

CREATE TABLE produto (
    idProduto INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria INT NOT NULL REFERENCES categoria(idCategoria),
    id_fornecedor INT NOT NULL REFERENCES fornecedor(idFornecedor),
    nome VARCHAR(128) NOT NULL,
    preco_compra FLOAT(20),
    margem_lucro FLOAT(20),
    descontinuado FLOAT(20),
    dt_fabric DATE NOT NULL,
    dt_validade DATE NOT NULL
);


CREATE TABLE telefones_empregado (
    matricula INT,
    numero INT,
    codigo INT,
    operadora VARCHAR(20) NOT NULL,
    PRIMARY KEY (matricula, numero),
    FOREIGN KEY (matricula) REFERENCES empregado(matricula)
);

CREATE TABLE telefones_transportadora (
    idTransportadora INT,
    numero INT,
    codigo INT,
    operadora VARCHAR(20) NOT NULL,
    PRIMARY KEY (idTransportadora, numero),
    FOREIGN KEY (idTransportadora) REFERENCES transportadora(idTransportadora)
);

CREATE TABLE regiao (
    idRegiao INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL
);

CREATE TABLE dependentes (
    idDependente INT,
    idCliente INT,
    nome VARCHAR(128) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    dt_nascimento DATE NOT NULL,
    PRIMARY KEY (idDependente, idCliente),
    FOREIGN KEY (idCliente) REFERENCES cliente(idCliente)
);

CREATE TABLE venda_produtos (
    idVenda INT,
    idProduto INT,
    preco_unitario FLOAT(20),
    quantidade INT,
    desconto FLOAT(20),
    PRIMARY KEY (idVenda, idProduto),
    FOREIGN KEY (idVenda) REFERENCES venda(idVenda),
    FOREIGN KEY (idProduto) REFERENCES produto(idProduto)
);

CREATE TABLE atuacao_empregado (
    matricula INT,
    idRegiao INT,
    PRIMARY KEY (matricula, idRegiao),
    FOREIGN KEY (matricula) REFERENCES empregado(matricula),
    FOREIGN KEY (idRegiao) REFERENCES regiao(idRegiao)
);

