CREATE TABLE cliente (
    idCliente INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    sobrenome VARCHAR(128) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    titulo_tratamento VARCHAR(10) NOT NULL,
    dt_nascimento VARCHAR(9) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    rua VARCHAR(128) NOT NULL,
    num INT,
    bairro VARCHAR(128) NOT NULL,
    cidade VARCHAR(128) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    pais VARCHAR(20) NOT NULL,
    cep VARCHAR(10) NOT NULL
);

CREATE TABLE empregado (
    matricula INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mat_supervisor INT NOT NULL REFERENCES empregado(matricula),
    nome VARCHAR(128) NOT NULL,
    funcao VARCHAR(128) NOT NULL,
    dt_nascimento VARCHAR(128) NOT NULL,
    dt_contato VARCHAR(128) NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    salario FLOAT(20)

);
/*
CREATE TABLE telefones_empregado (
    matricula,
    numero,
    codigo INT,
    operadora VARCHAR(20) NOT NULL

);

CREATE TABLE telefones_transportadora (
    idTransportadora,
    numero ,
    codigo INT,
    operadora VARCHAR(20) NOT NULL
);
*/
CREATE TABLE transportadora (
    idTransportadora INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL
);

CREATE TABLE venda (
    idVenda INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL REFERENCES cliente(idCliente),
    id_transportadora INT NOT NULL REFERENCES transportadora(idTransportadora),
    matricula INT NOT NULL REFERENCES empregado(matricula),
    frete VARCHAR(128) NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    dt_entrega VARCHAR(10) NOT NULL
);

CREATE TABLE produto (
    idProduto INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria INT NOT NULL REFERENCES categoria(idCategoria),
    id_fornecedor INT NOT NULL REFERENCES fornecedor(idFornecedor),
    nome VARCHAR(128) NOT NULL,
    preco_compra FLOAT(20),
    margem_lucro FLOAT(20),
    descontinuado FLOAT(20),
    dt_fabric VARCHAR(10) NOT NULL,
    dt_validade VARCHAR(10) NOT NULL
);

CREATE TABLE categoria (
    idCategoria INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL
);

CREATE TABLE regiao (
    idRegiao INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL
);

CREATE TABLE fornecedor (
    idFornecedor INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    endereco VARCHAR(128) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    homepage VARCHAR(128) NOT NULL
);

/*
CREATE TABLE dependentes (
    idDependente,
    idCliente,
    nome VARCHAR(128) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    dt_nascimento VARCHAR(10) NOT NULL
);

CREATE TABLE venda_produtos (
    idVenda,
    idProduto,
    preco_unitario FLOAT(20),
    quantidade INT,
    desconto FLOAT(20)
);

CREATE TABLE atuacao_empregado (
    CONSTRAINT PK_ATUA_USUARIO PRIMARY KEY (matricula, idRegiao)
);

*/


